version: '3.2'

services:
    
    php-stan:
        build:
            context: ./docker-context
            dockerfile: php-stan/Dockerfile
        volumes:
            - ${STOPWATCH_DIR}/:/app:ro
            
    php-cs-fixer:
        build:
            context: ./docker-context
            dockerfile: php-cs-fixer/Dockerfile
        volumes:
            - ${STOPWATCH_DIR}/:/app
            
    xdebug:
        build:
            context: ./docker-context
            dockerfile: xdebug/Dockerfile
        volumes:
            - ${STOPWATCH_DIR}/:/app:ro
            # xdebug logs
            - ./data/xdebug/:/tmp/xdebug
            # xdebug settings
            - ./docker-context/xdebug/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            
    composer:
        build:
            context: ./docker-context
            dockerfile: composer/Dockerfile
        environment:
            - COMPOSER_ALLOW_XDEBUG=0
            - PHP_ENABLE_XDEBUG=0
        volumes:
            - ${STOPWATCH_DIR}/:/app
            # Composer cache
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
    
    rector:
        build:
            context: ./docker-context
            dockerfile: rector/Dockerfile
        environment:
            - PHP_ENABLE_XDEBUG=0
        volumes:
            - ${STOPWATCH_DIR}/:/app
            # Composer cache
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
    
    swiss-knife:
        build:
            context: ./docker-context
            dockerfile: swiss-knife/Dockerfile
        environment:
            - PHP_ENABLE_XDEBUG=0
        volumes:
            - ${STOPWATCH_DIR}/:/app
            # Composer cache
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            
    php-unit:
        build:
            context: ./docker-context
            dockerfile: php-unit/Dockerfile
        volumes:
            - ${STOPWATCH_DIR}/:/app:ro
            - ./data/php-unit/coverage/report/:/tmp/coverage/report

    php-unit-8:
        build:
            context: ./docker-context
            dockerfile: php-unit-8/Dockerfile
        volumes:
            - ${STOPWATCH_DIR}/:/app:ro
            
    infection:
        build:
            context: ./docker-context
            dockerfile: infection/Dockerfile
        volumes:
            - ${STOPWATCH_DIR}/:/app
            - ./data/infection:/infection

